#! /bin/bash

PROJECT=metis

VERSION=2.1

APPHOME="$(dirname $(dirname $0))"

APPNAME=$(basename $0)

LOGSIZE=51200

LOGFILE=/data/log/$PROJECT/$APPNAME.log

TIMEOUT=30

# get real-username & IP
REALUSER=`who am i | awk '{print $1}'`
REALTTYS=`who am i | awk '{print $2}'`
REALIPAD=`who am i | awk -F '(' '{print $2}' | awk -F ')' '{print $1}'`


if [ "$REALIPAD" = ":0.0" ] || [ "$REALIPAD" = ":0" ]
then
    REALIPAD="127.0.0.1"
fi 

# set temp dir 
if [ -d /dev/shm ] && [ -w /dev/shm ]
then
    APPTEMP=/dev/shm/$PROJECT
else
    APPTEMP=/tmp/$PROJECT
fi
test -d $APPTEMP || mkdir -m 1777 -p $APPTEMP

# defined database
MYSQL_NAME='metis'
MYSQL_USER='metis'
MYSQL_PASS='DHS3SdkSxXvCUggP'
MYSQL_HOST='127.0.0.1'
MYSQL_NAME='metis'
MYSQL_CONN='/usr/bin/mysql'
MYSQL_EXEC="$MYSQL_CONN -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASS"

# Backup settings
BACKUP_WEB_LIST=$APPHOME/cfg/backup.web.list
