#! /bin/bash
# defined project name
PROJECT=metis

# defined version
VERSION=2.1

# defined Application home
APPHOME="$(dirname $(dirname $0))"

# defined Application name
APPNAME=$(basename $0)

# set log file size
LOGSIZE=51200

# set log file path
LOGFILE=/data/log/$PROJECT/$PROJECT.log

# defined timed-out(sec)
TIMEOUT=30

# get real-username & IP
REALUSER=`who am i | awk '{print $1}'`
REALTTYS=`who am i | awk '{print $2}'`
REALIPAD=`who am i | awk -F '(' '{print $2}' | awk -F ')' '{print $1}'`

if [ "$REALIPAD" = ":0.0" ] || [ "$REALIPAD" = ":0" ]
then
    REALIPAD="127.0.0.1"
fi 

# set temp dir 
if [ -d /dev/shm ] && [ -w /dev/shm ]
then
    APPTEMP=/dev/shm/$PROJECT
else
    APPTEMP=/tmp/$PROJECT
fi
test -d $APPTEMP || mkdir -m 1777 -p $APPTEMP

# defined database
MYSQL_USER='metis'
MYSQL_PASS='DHS3SdkSxXvCUggP'
MYSQL_HOST='127.0.0.1'
MYSQL_NAME='metis'
MYSQL_CONN='/usr/local/bin/mysql'
MYSQL_EXEC="$MYSQL_CONN -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASS"