#! /bin/bash

# check

check(){
    for check_arg in "$@"
    do
        case "$check_arg" in 
            input)
                chk_input="$2"
                if [ "X$chk_input" = "X" ]
                then
                    log  error "Error: No input detected"
                    abort
                fi
                shift 2
                ;;
            #syntax)
            accept)
                chk_accept="$2"
                if [ "X$chk_accept" = "X" ]
                then
                    log error "Error: Accept type not defined"
                    abort
                fi
                echo "$chk_input" | egrep -q "$chk_accept"
                if [ "$?" != 0 ]
                then
                    log error "Error: Accept type not support"
                    abort
                fi
                ;;
            #command)
            #perm)
            #option)
            read)
            write)
            file)
            dir)
            exist)
            empty)
            pipe)
            socket)
            size)
        esac
    done
}
