#! /bin/bash

# check
# common check

check(){
    for chkarg in "$@"
    do
        case "$chkarg" in 
            input)
                if [ "X$2" = "X" ]
                then
                    log error "Error: No input detected"
                    abort
                else
                    return 0
                fi
                ;;
            #syntax)
            #login)
                # login
            #    ;;
            accept)
                echo "$2" | egrep -q "$3"
                if [ "$?" != 0 ]
                then
                    log error "Error: Unsupported type"
                    abort
                else
                    return 0
                fi
                ;;
            command)
                command="$2"
                ;;
            #perm)
            #option)
            file)
                if [ -e "$2" ]
                then
                    if [ ! -f "$2" ]
                    then
                        log error "Error: $2: Not a regular file"
                        abort
                    fi
                    if [ ! -r "$2" ]
                    then
                        log error "Error: $2: Permission denied"
                        abort
                    fi
                    return 0
                else
                    log error "Error: $2: File not found"
                    abort
                fi
                ;;
            dir);;
            exist)
                if [ ! -e "$2" ]
                then
                    log error "Error: $2: does not exist"
                    abort
                fi
                ;; 
            empty);;
                
            pipe);;
            socket);;
            size);;
            type);;
            sql);;
        esac
    done
}
