#! /bin/bash

# check
# common check
check_arg(){
    if [ "X$1" = "X" ]
    then
        log error "Error: $check_arg: $2"
        abort
    fi
} 

check(){
    for chkarg in "$@"
    do
        case "$chkarg" in 
            input)
                check_arg "$2" "No input detected"
                shift 2
                ;;
            #syntax)
            #login)
                # login
            #    ;;
            accept)
                check_arg "$2" "Accept type not defined"
                echo "$2" | egrep -q "$chk_accept"
                if [ "$?" != 0 ]
                then
                    log error "Error: Accept type not support"
                    abort
                fi
                ;;
            #command)
            #perm)
            #option)
            read)
                check_arg "$2" "Require argument"
                ;;    
            write)
            file)
            dir)
            exist)
                if [ ! -e "$2" ]
                then
                    log error "Error: $2: does not exist"
                    abort
                fi
                ;; 
            empty)
                
            pipe)
            socket)
            size)
            type)
        esac
    done
}
