#! /bin/bash
#echo -e "192.168.200.10 22 test-app-1"

db(){
    case $1 in 
        #info)
            
        server)
        ;;    
        group)
        ;;
        add)
        ;;
        edit)
        ;;
        delete)
        ;;
        get)
        ;;
    esac
}
