#! /bin/bash

app_home="$(dirname $(dirname $0))"
 fun_log="$app_home/fun/log"

if [ -f "$fun_log" ]
then
    . $fun_log
else
    echo -e "\033[1;41mError:\033[0m Unable to load module $fun_log: File not found"
    exit 1
fi

load(){
	## load metis:cfg:settings
	## load login from metis:bin:gt
	
    settings="$app_home/cfg/settings"

    if [ -f $settings ]
    then
        . $settings
    else
        echo -e "\033[1;41mError\033[0m: 'settings' Not Found"
        exit 1
    fi

    arg="$@"
    tmp=`mktemp $APPTEMP/XXXXXXXXXXXXXXXX`
    echo "$arg" | grep -q ' from '
    if [ $? = 0 ]
    then
        fun=`echo "$arg" | awk -F ' from ' '{print $1}'`
        tgt=`echo "$arg" | awk -F ' from ' '{print $2}'`
        
          f="$(dirname $APPHOME)/`echo $tgt | sed 's/\:/\//g'`"

        if [ -f "$f" ]
        then
            if [ -r "$f" ]
            then
                grep -q "^$fun(){$" $f
                if [ $? = 0 ]
                then
                    sed -n "/^$fun(){\$/,/^}\$/p" $f > $tmp
                    . $tmp && rm -rf $tmp
                else
                    log error "Cannot load $tgt: Function not defined"
                    exit 1
                fi
            else
                log error "Cannot load $tgt: Permission Denied"
                exit 1
            fi
        else
            log error "Cannot load $tgt: File not found"
            exit 1
        fi
    else
        f="$(dirname $APPHOME)/`echo $arg | sed 's/\:/\//g'`"

        if [ -f "$f" ]
        then
            if [ -r "$f" ]
            then
                . $f
            else
                log error "Cannot load $arg: Permission Denied"
                exit 1
            fi
        else
            log error "Cannot load $arg: File not found"
            exit 1
        fi
    fi
}
