#! /bin/bash

log(){
    # log level(error|warn|info) msg
    LOGLEVEL="$1"
    LOG_TEXT="$2"
    LOG_TLTE=""

    test -z "$LOGFILE" && LOGFILE=$LOGHOME/${APPNAME}-`date +%Y-%m`.log
    test -d "$(dirname $LOGFILE)" || mkdir "$(dirname $LOGFILE)"
    
    echo -e "`date +'%F %T.%N'` $LOGLEVEL $USER($REALUSER:$REALTTYS:$REALIPAD): $2" >> $LOGFILE
    
    test $LOGLEVEL = "error" && LEV_TLE="\033[1;41m Error: \033[0m"
    test $LOGLEVEL = "warn"  && LEV_TLE="\033[1;33m Warning : \033[0m"
    
    if [ "$LOGLEVEL" = "error" ] || [ "$LOGLEVEL" = "warn" ]
    then
        echo -e "$LEV_LTE $LOG_TEXT"
    else
        echo -e "$LOG_TEXT"
    fi
}
