#! /bin/bash

# nginx config finder

app_ngx_root_dir_by_defined(){
    check read $Ngxconf

    for ngx_root_dir in `grep '^ * root ' $Ngxconf | awk '{print $2}' | awk -F ';' '{print $1}'`
    do
        test -d $ngx_root_dir && echo $ngx_root_dir
    done

    for ngx_cnf_inc in `grep '^ * include ' $Ngxconf | awk -F 'include ' '{print $2}' | awk -F ';' '{print $1}'`
    do
        ngx_root_dir=`grep '^ * root ' $(dirname $Ngxconf)/$ngx_cnf_inc | awk -F 'root ' '{print $2}' | awk -F ';' '{print $1}'`
        test -d $ngx_root_dir && echo $ngx_root_dir
    done
} 


