#! /usr/bin/env python

"""
String test

Usage: 
    is  argument string

        alnum
        alpha
        ascii
        blank
        cntrl
        digit
        graph
        print
        lower
        upper
        hexad 
"""

import sys

argv   = sys.argv[1]
string = sys.argv[2]

if   argv == 'alnum':
     print string.isalnum()

elif argv == 'alpha':
     print string.isalpha()
    
elif argv == 'ascii':
     print string.isascii()
    
elif argv == 'blank':
     print string.isblank()
     
elif argv == 'cntrl':
     print string.iscntrl()

elif argv == 'digit':
     print string.isdigit()
 
elif argv == 'graph':
     print string.isgraph()
    
elif argv == 'print':
     print string.isprint()
    
elif argv == 'lower':
     print string.islower()
    
elif argv == 'space':
     print string.isspace()
    
elif argv == 'upper':
     print string.isupper()
    
elif argv == 'hexad':
     print string.isxdigit()
    
else:
     print __doc__
     sys.exit(1)
