#! /usr/bin/env python

import sys

argv   = sys.argv[1]
string = sys.argv[2]

if   argv == 'alnum':
     print string.isalnum()

elif argv == 'alpha':
     print string.isalpha()
    
elif argv == 'ascii':
     print string.isascii()
    
elif argv == 'blank':
     print string.isblank()
     
elif argv == 'cntrl':
     print string.iscntrl()

elif argv == 'digit':
     print string.isdigit()
     
elif argv == 'graph':
     print string.isgraph()
    
elif argv == 'print':
     print string.isprint()
    
elif argv == 'lower':
     print string.islower()
    
elif argv == 'space':
     print string.isspace()
    
elif argv == 'upper':
     print string.isupper()
    
elif argv == 'hexad':
     print string.isxdigit()
    
else:
     print '127'
     sys.exit(1)
